### ISSUE TITLE
FEAT - jupyterlab-accessible-themes extension - first iteration

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyterlab-accessible-themes#40]
After #39 - work on `jupyterlab-accessible-themes` extension bundling the new accessible pygments themes - with inspiration from [jupyterlab-fonts](https://github.com/deathbeds/jupyterlab-fonts)

```[tasklist]
### Themes
- [x] Port [Pitaya Smoothie](https://github.com/trallard/jupyterlab-pitaya-smoothie) from JLab 2 to 3
- [x] [GitHub VSCode - light default](https://github.com/primer/github-vscode-theme) - https://github.com/Quansight-Labs/jupyterlab-accessible-themes/pull/49
- [ ] [Github VSCode - dark default](https://github.com/primer/github-vscode-theme)
- [ ] Create a release for the themes extension
- [ ] [Github VSCode - dark high contrast](https://github.com/primer/github-vscode-theme)
- [ ] [Github VSCode - light high contrast](https://github.com/primer/github-vscode-theme)
```

**Comment by trallard** [comment]
@steff456 can you work on these iterateively? i.e. one at a time, so we can keep small, well-scoped PRs and releases?

**Comment by steff456** [comment]
Sure! I'm working in the first one and I think it is also best to do it in an incremental fashion.

**Comment by trallard** [comment]
@steff456 - it would make sense to start working on the Dark GH theme also
