### ISSUE TITLE
Other variations of syntax highlighting to explore for accessible-pygments

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/jupyterlab-accessible-themes#41]
From #38 

  - high contrast themes
  - Verify the "accessible themes" [suggested by VSCode](https://code.visualstudio.com/docs/editor/accessibility), namely:
    - [GitHub](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme): Accessible to most forms of colourblindness and matches the themes in GitHub's settings.
    - [Gotthard](https://marketplace.visualstudio.com/items?itemName=janbiasi.gotthard-theme): Optimized for approximately 20 programming languages.
[Blinds](https://marketplace.visualstudio.com/items?itemName=tankashing.blinds-theme). Created with Deuteranopia in mind and possesses a high contrast colour ratio.
    - [Greative](https://marketplace.visualstudio.com/items?itemName=Greative.greative). Considers both colourblindness and light sensitivity.

Some of these styles are also optimised for colourblindness and light sensitivity, so it is worth considering. 
And ofc because I am biased, and I made sure that the colours in [pitaya-smoothie](https://github.com/trallard/pitaya_smoothie) are WCAG compliant and colourblind friendly too, I'd also like to propose adding this to the package

**Comment by steff456** [comment]
Closing this issue given that all the themes were added -> https://github.com/Quansight-Labs/accessible-pygments/issues/13
