### ISSUE TITLE
The conda-forge package is not working -- and the instructions have the wrong name for it

### ISSUE THREAD

**Issue by mjkanji** [Quansight-Labs/jupyterlab-accessible-themes#69]
Hi there!

The installation instructions for the conda package in the README are:

```bash
conda install -c conda-forge jupyterlab_accessible_themes
```

However, the name of the package in conda-forge is actually [`jupyterlab-accessible-themes`](https://anaconda.org/conda-forge/jupyterlab-accessible-themes) (it uses dashes, not underscores).

Also, the conda version is not detected by JupyterLab correctly:

```bash
micromamba create -n temp -y python=3.10 "jupyterlab<4" jupyterlab-accessible-themes
micromamba activate temp
jupyter labextension list

# Prints:
# JupyterLab v3.6.5
# /home/ubuntu/micromamba/envs/temp/share/jupyter/labextensions
#         jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
```

Note that the accessible themes are not listed. However, the pip version works fine:

```bash
# This is a new environment
micromamba create -n temp -y python=3.10 "jupyterlab<4"
micromamba activate temp
pip install jupyterlab_accessible_themes
jupyter labextension list

# Prints:
JupyterLab v3.6.5
# /home/ubuntu/micromamba/envs/temp/share/jupyter/labextensions
#         jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
#         @jupyterlab-accessible-themes/jupyterlab-theme-githublight v0.1.0 enabled OK
#         @jupyterlab-accessible-themes/jupyterlab-theme-pitayasmoothie v0.1.0 enabled OK
```

**Comment by trallard** [comment]
Thanks for reporting these issues @mjkanji I am only seeing this so apologies for the delay. We are working on the package and hope to have a fix for this soon.

**Comment by steff456** [comment]
This issue should be fixed with the latest release, it is already available in the conda-forge channel. @mjkanji can you please try it and let me know if you still encounter the same issue?

**Comment by steff456** [comment]
Closing this issue because the package is now working on conda 🎉
